name: CI
on:
  push:
    branches:
      - main
  pull_request:

env:
  NX_CLOUD_DISTRIBUTED_EXECUTION: true

jobs:
  main:
    name: Nx Cloud - Main Job
    uses: nrwl/ci/.github/workflows/nx-cloud-main.yml@v0.5
    with:
      number-of-agents: 3
      parallel-commands: |
        NX_CLOUD_DISTRIBUTED_EXECUTION npx nx-cloud record -- npx nx workspace-lint
        NX_CLOUD_DISTRIBUTED_EXECUTION npx nx-cloud record -- npx nx format:check
      parallel-commands-on-agents: |
        NX_CLOUD_DISTRIBUTED_EXECUTION npx nx affected --target=lint --parallel=3
        NX_CLOUD_DISTRIBUTED_EXECUTION npx nx affected --target=test --parallel=3 --ci --code-coverage
        NX_CLOUD_DISTRIBUTED_EXECUTION npx nx affected --target=build --parallel=3

  agents:
    name: Nx Cloud - Agents
    uses: nrwl/ci/.github/workflows/nx-cloud-agents.yml@v0.5
    with:
      number-of-agents: 3